# Generated by Django 6.0.2 on 2026-02-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rango", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default=""),
            preserve_default=False,
        ),
    ]
